name: publish

on:
  release:
    types: [released]

permissions:
  contents: write    # Право на создание релиза в GitHub
  id-token: write    # МАГИЯ OIDC: Право получать "паспорт" от GitHub

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: latest
          registry-url: 'https://registry.npmjs.org'
      - run: npm install
      - run: npm run build
      - run: npm run prepack
      - run: npm publish --tag latest
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: npm run postpack
      - name: Pack Tarballs
        run: npx oclif pack:tarballs
      - name: Pack Debian
        run: npx oclif pack:deb
      - name: Generate SHA256 Hashes
        run: shasum -a 256 dist/*.tar.gz
      - name: Upload to GitHub Releases
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/*.tar.gz
            dist/*.deb