name: publish

on:
  release:
    types: [ released ]

permissions:
  contents: write
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'

      - run: npm install

      - run: npm run build

      - run: npm run prepack

      - run: npm publish --tag latest --provenance

      - run: npm run postpack

      - name: Pack Tarballs
        run: npx oclif pack:tarballs

      - name: Pack Debian
        run: npx oclif pack:deb

      - name: Generate SHA256 Hashes
        run: shasum -a 256 dist/*.tar.gz

      - name: Upload to GitHub Releases
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/*.tar.gz
            dist/*.deb

      - name: Setup Homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Update Homebrew Tap Natively
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAP_GITHUB_TOKEN: ${{ secrets.TAP_GITHUB_TOKEN }}
        run: |
          VERSION=${GITHUB_REF_NAME#v}
          brew tap razomy/tap https://${TAP_GITHUB_TOKEN}@github.com/razomy/homebrew-tap.git
          brew bump-formula-pr --write-only --version=${VERSION} razomy
          cd $(brew --repo razomy/tap)
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git commit -am "Bump razomy to ${VERSION}"
          git push