name: publish

on:
  release:
    types: [ released ]

permissions:
  contents: write
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 24
          registry-url: 'https://registry.npmjs.org'

      - run: npm install

      - run: npm run build

      - run: npm run prepack

#      - run: npm publish --tag latest --access public --provenance
#        env:
#          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: npm run postpack

      - name: Pack Tarballs
        run: npx oclif pack:tarballs

      - name: Pack Debian
        run: npx oclif pack:deb

      - name: Generate SHA256 Hashes
        run: shasum -a 256 dist/*.tar.gz

      - name: Upload to GitHub Releases
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/*.tar.gz
            dist/*.deb
      - name: Update Homebrew Tap
        env:
          TAP_GITHUB_TOKEN: ${{ secrets.TAP_GITHUB_TOKEN }}
        run: |
          # Экспортируем переменные, чтобы утилита envsubst их увидела
          export VERSION=${GITHUB_REF_NAME#v}
          export TAG=${GITHUB_REF_NAME}
          
          export MAC_X64_FILE=$(basename $(ls dist/*-darwin-x64.tar.gz))
          export MAC_ARM64_FILE=$(basename $(ls dist/*-darwin-arm64.tar.gz))
          export LINUX_X64_FILE=$(basename $(ls dist/*-linux-x64.tar.gz))
          export LINUX_ARM64_FILE=$(basename $(ls dist/*-linux-arm64.tar.gz))
          
          export MAC_X64_SHA=$(shasum -a 256 dist/$MAC_X64_FILE | awk '{print $1}')
          export MAC_ARM64_SHA=$(shasum -a 256 dist/$MAC_ARM64_FILE | awk '{print $1}')
          export LINUX_X64_SHA=$(shasum -a 256 dist/$LINUX_X64_FILE | awk '{print $1}')
          export LINUX_ARM64_SHA=$(shasum -a 256 dist/$LINUX_ARM64_FILE | awk '{print $1}')
          
          # Клонируем Tap
          git clone https://${TAP_GITHUB_TOKEN}@github.com/razomy/homebrew-tap.git tap
          
          mkdir -p tap/Formula
          
          # МАГИЯ ЗДЕСЬ: envsubst берет ваш шаблон, подставляет переменные и сохраняет в tap!
          envsubst < .github/razomy.rb.template > tap/Formula/razomy.rb
          
          # Пушим
          cd tap
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add Formula/razomy.rb
          
          if ! git diff --staged --quiet; then
            git commit -m "Bump razomy to ${VERSION}"
            git push
            echo "✅ Formula успешно обновлена!"
          else
            echo "⚡ Изменений нет."
          fi
